<a href="https://colab.research.google.com/github/MuhammadSaadKhan1100/ML_Process_Course/blob/main/ML_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ** Machine Learning Assignment#1 🤖**
* Name: Muhammad Saad Khan
* Registration no.339315
* Department: EE
* Syndicate C

# **Dimensionality Reduction of Iris Dataset using PCA🤠**

* Step 1 **Loading Dataset in Pandas dataframe 🥣**

In [232]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer


from sklearn import datasets
from sklearn.decomposition import PCA
from scipy.linalg import eigh
dataset = datasets.load_iris()
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [233]:
data = pd.DataFrame(dataset.data, columns = dataset.feature_names)
target_class = list(dataset.target)

iris_target_names = {i : dataset.target_names[i] for i in range(0, len(dataset.target_names))}
target = list(map(iris_target_names.get,target_class))
y = dataset.target


* Step 2 **Now Printing out dataset 💻**

In [234]:
print(data.shape)
print(y.shape)

(150, 4)
(150,)


In [235]:
data.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

* Step 3 **Standardizing dataset (Scaling) i.e making mean = 0** ⚖

In [236]:
from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(dataset.data)
print(x)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

**Applying Principal Component Analysis**
* Step 4 **Finding Covariance Matrix**👀

In [237]:
# Step 4: Find covariance matrix
covariance_matrix = np.cov(x, rowvar=False)
covariance_matrix

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [238]:
from sklearn.decomposition import PCA
pca = PCA()
principalComponets = pca.fit_transform(x)

principalComponents = pd.DataFrame(principalComponets)
print(principalComponents.shape)
principalComponents.head(5)

(150, 4)


0         1         2         3
0 -2.264703  0.480027 -0.127706 -0.024168
1 -2.080961 -0.674134 -0.234609 -0.103007
2 -2.364229 -0.341908  0.044201 -0.028377
3 -2.299384 -0.597395  0.091290  0.065956
4 -2.389842  0.646835  0.015738  0.035923

* Step:5 **Finding Eigenvalues and Eigen Vectors** ✨🎇

In [239]:
# Step 5: Find eigenvalues and eigenvectors of the covariance matrix
eigenvalues, eigenvectors = eigh(covariance_matrix, eigvals=(0, len(covariance_matrix)-1))

print("Eigenvalues for the covariance of given iris data are ", list(np.round(eigenvalues,decimals = 5)), end = '\n\n')
print("Eigenvectors for the covariance of given iris data are ")
eigenvectors

Eigenvalues for the covariance of given iris data are  [0.02085, 0.14774, 0.92016, 2.93809]

Eigenvectors for the covariance of given iris data are 


<ipython-input-239-13e97dd09076>:2: DeprecationWarning: Keyword argument 'eigvals' is deprecated in favour of 'subset_by_index' keyword instead and will be removed in SciPy 1.12.0.
  eigenvalues, eigenvectors = eigh(covariance_matrix, eigvals=(0, len(covariance_matrix)-1))


array([[ 0.26128628,  0.71956635, -0.37741762,  0.52106591],
       [-0.12350962, -0.24438178, -0.92329566, -0.26934744],
       [-0.80144925, -0.14212637, -0.02449161,  0.5804131 ],
       [ 0.52359713, -0.63427274, -0.06694199,  0.56485654]])

* Step: 6 **Arranging in Descending order** 🌊

In [240]:
# Step 6: Arrange eigenvalues in descending order
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

# **Descending Eigenvalues:**

In [241]:
eigenvalues

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

# **Corresponding Eigen vectors:**

In [242]:
eigenvectors

array([[ 0.52106591, -0.37741762,  0.71956635,  0.26128628],
       [-0.26934744, -0.92329566, -0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161, -0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199, -0.63427274,  0.52359713]])

In [243]:
eigenvectorsn = pd.DataFrame(abs(pca.components_[:2]), columns = dataset.feature_names,
                     index = ['Principal Component 1', 'Principal Component 2'])
eigenvectorsn

sepal length (cm)  sepal width (cm)  petal length (cm)  \
Principal Component 1           0.521066          0.269347           0.580413   
Principal Component 2           0.377418          0.923296           0.024492   

                       petal width (cm)  
Principal Component 1          0.564857  
Principal Component 2          0.066942

* Step:7 **Selecting Eigenvalues with 95% Variance**

In [244]:
# Step 7: Select eigenvalues that retain the required variance
total_variance = np.sum(eigenvalues)
explained_variance_ratio = eigenvalues / total_variance
cumulative_explained_variance_ratio = np.cumsum(explained_variance_ratio)

In [245]:
# Find the number of components that retain 95% variance
num_components_retained = np.argmax(cumulative_explained_variance_ratio >= 0.95) + 1

In [246]:
num_components_retained

2

* Step:8 **Transformed Matrix**

In [249]:
# Step 6: Transform original data using selected eigenvectors
selected_eigenvectors = eigenvectors[:, :num_components_retained]
X_pca = np.dot(x, selected_eigenvectors)
X_pca

array([[-2.26470281, -0.4800266 ],
       [-2.08096115,  0.67413356],
       [-2.36422905,  0.34190802],
       [-2.29938422,  0.59739451],
       [-2.38984217, -0.64683538],
       [-2.07563095, -1.48917752],
       [-2.44402884, -0.0476442 ],
       [-2.23284716, -0.22314807],
       [-2.33464048,  1.11532768],
       [-2.18432817,  0.46901356],
       [-2.1663101 , -1.04369065],
       [-2.32613087, -0.13307834],
       [-2.2184509 ,  0.72867617],
       [-2.6331007 ,  0.96150673],
       [-2.1987406 , -1.86005711],
       [-2.26221453, -2.68628449],
       [-2.2075877 , -1.48360936],
       [-2.19034951, -0.48883832],
       [-1.898572  , -1.40501879],
       [-2.34336905, -1.12784938],
       [-1.914323  , -0.40885571],
       [-2.20701284, -0.92412143],
       [-2.7743447 , -0.45834367],
       [-1.81866953, -0.08555853],
       [-2.22716331, -0.13725446],
       [-1.95184633,  0.62561859],
       [-2.05115137, -0.24216355],
       [-2.16857717, -0.52714953],
       [-2.13956345,

* Step:9 **Components retained and Variance ratio**

In [248]:
# Print the results
print(f"Number of components retained: {num_components_retained}")
print(f"Explained variance ratio: {cumulative_explained_variance_ratio[num_components_retained - 1]:.4f}")

Number of components retained: 2
Explained variance ratio: 0.9581


# *** Conclusion:***🎨

In this task, we successfully applied Principal Component Analysis (PCA) to the Iris dataset, reducing its dimensionality while retaining 95% variance. After mean normalization, computation of the covariance matrix, and extraction of eigenvalues and eigenvectors, the original data was transformed using the selected eigenvectors. The code aimed to achieve efficient dimension reduction, demonstrating the steps in a clear and concise manner for effective implementation.